### ISSUE TITLE
SOQL.Filter.with(Account.Name).contains(null); throws NullPointerException

### ISSUE THREAD

**Issue by Aschalin** [beyond-the-cloud-dev/soql-lib#116]
new version of library has issue with contains(null)
<img width="399" alt="Screenshot 2024-04-30 at 17 19 56" src="https://github.com/beyond-the-cloud-dev/soql-lib/assets/11525497/a2d9a663-ac68-4574-9d7f-2836753bb0ce">
old version(marked green on screenshot bellow) of formattedString method was working with null values
<img width="918" alt="Screenshot 2024-04-30 at 17 19 17" src="https://github.com/beyond-the-cloud-dev/soql-lib/assets/11525497/1c74e968-89ce-42e9-b357-4b4f9f630916">

**Comment by pgajek2** [comment]
Thank you @Aschalin ! Code fixed. You can find the newest version on the main branch. Please let me know if it works as expected.
