### ISSUE TITLE
exception is thrown when more than 9 FilterGroups

### ISSUE THREAD

**Issue by Aschalin** [beyond-the-cloud-dev/soql-lib#122]
example:
```
SOQL.of(Account.SObjectType)
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('1')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('2')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('3')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('4')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('5')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('6')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('7')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('8')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('9')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('0')))
.whereAre(SOQL.FilterGroup.add(SOQL.Filter.with(Account.Name).contains('a')))
.preview()
.toList();
```

preview result:
`14:35:31:000 USER_DEBUG WHERE (Name LIKE :v1) AND (Name LIKE :v2) AND (Name LIKE :v3) AND (Name LIKE :v4) AND (Name LIKE :v5) AND (Name LIKE :v6) AND (Name LIKE :v7) AND (Name LIKE :v8) AND (Name LIKE :v9) AND (Name LIKE :v1)0 AND (Name LIKE :v1)(Name LIKE :v1)`
![Screenshot 2024-05-13 at 14 39 57](https://github.com/beyond-the-cloud-dev/soql-lib/assets/11525497/11bac1fa-3364-4fc5-aa09-a3c515637781)

expected preview result:
`14:35:31:000 USER_DEBUG WHERE (Name LIKE :v1) AND (Name LIKE :v2) AND (Name LIKE :v3) AND (Name LIKE :v4) AND (Name LIKE :v5) AND (Name LIKE :v6) AND (Name LIKE :v7) AND (Name LIKE :v8) AND (Name LIKE :v9) AND (Name LIKE :v10) AND (Name LIKE :v11)`

exception:
![Screenshot 2024-05-13 at 14 44 17](https://github.com/beyond-the-cloud-dev/soql-lib/assets/11525497/c28ca58f-62a3-41f7-99af-af281e4ac891)

**Comment by pgajek2** [comment]
Hi @Aschalin ,

Here is the fix: https://github.com/beyond-the-cloud-dev/soql-lib/pull/123

**Comment by pgajek2** [comment]
@Aschalin code on the main branch.
