### ISSUE TITLE
System.FinalException: Cannot modify a collection while it is being iterated.

### ISSUE THREAD

**Issue by jdkgabri** [beyond-the-cloud-dev/soql-lib#131]
I just ran into this exception when trying to deploy these classes and execute their tests:

Class Name | Method Name | Error Message
-- | -- | --
SOQL_Test | countSObjectFieldWithDefaultFields | System.FinalException: Cannot modify a collection while it is being iterated.Stack Trace: Class.SOQL.SoqlFields.removeNotGroupedFields: line 1135, column 1 Class.SOQL.SoqlFields.toString: line 1122, column 1 Class.SOQL.QueryBuilder.toString: line 943, column 1 Class.SOQL.toString: line 791, column 1 Class.SOQL_Test.countSObjectFieldWithDefaultFields: line 74, column 1
SOQL_Test | groupByWithDefaultFields | System.FinalException: Cannot modify a collection while it is being iterated.Stack Trace: Class.SOQL.SoqlFields.removeNotGroupedFields: line 1135, column 1 Class.SOQL.SoqlFields.toString: line 1122, column 1 Class.SOQL.QueryBuilder.toString: line 943, column 1 Class.SOQL.toString: line 791, column 1 Class.SOQL_Test.groupByWithDefaultFields: line 1962, column 1

I believe it happends because the API version is 62. As explained here, its not allowed since version 61 onwards:

https://www.apexhours.com/preventing-collection-modification-during-iteration-in-apex/

After downgrading the API version of the meta-xml files of the classes to 60, it worked.

**Comment by pgajek2** [comment]
Hi @jdkgabri , 

Sorry for the late response. I am looking at it!

**Comment by pgajek2** [comment]
@jdkgabri 

Here is PR: https://github.com/beyond-the-cloud-dev/soql-lib/pull/133/files
Here is a branch: `131-systemfinalexception-cannot-modify-a-collection-while-it-is-being-iterated`

I will merge it to the `main` branch as a part of the next release, however you can use it now. 
Please let me know if everything works fine.
