### ISSUE TITLE
Removing requirement of ContactsToMultipleAccounts (AccountContactRelation) Feature to pass tests

### ISSUE THREAD

**Issue by mgellada-sd** [beyond-the-cloud-dev/soql-lib#77]
This has caused much headache with org deployment of using this great library! This is a feature that is not enabled and not planned to enable for org deployment. Is there a way to remove this requirement by changing tests to use something else that can exhibit same testing behavior so that this feature does not need to be enabled for deployment and running tests?

**Comment by pgajek2** [comment]
Thanks @mgellada-sd! Great point!

I see two option:
1. I can change it by myself
2. Or you can create PR from your forked repository 

Let's me know what do you prefer :D

**Comment by pgajek2** [comment]
Deployed! Thanks for collaboration @mgellada-sd 🫡
